-- Migration: Reseed experience_templates with the curated Adventurous list
-- Added on: 2026-05-13
-- Description: Replaces the initial broad seed with a focused set of 48
-- adventurous titles + hook lines provided by the product team.

DELETE FROM experience_templates;

INSERT INTO experience_templates (mood, title, hook_line) VALUES
    ('adventure', 'Chase the First Light',               'Some mornings are worth waking up for.'),
    ('adventure', 'Firelight & Strangers',               'Strangers feel closer around a fire.'),
    ('adventure', '48 Hours Offline',                    'The world can wait for two days.'),
    ('adventure', 'Sleep Under a Million Stars',         'The sky looks unreal out here.'),
    ('adventure', 'Into the Quiet Forest',               'Silence sounds better in the forest.'),
    ('adventure', 'Run to the Hidden Falls',             'Some places still feel undiscovered.'),
    ('adventure', 'Escape to Slow Life',                 'Life moves slower here.'),
    ('adventure', 'Edge of the World Camp',              'Wake up above the clouds.'),
    ('adventure', 'Lost Somewhere Beautiful',            'Getting lost never felt this good.'),
    ('adventure', 'Mountains & Mental Reset',            'Mountains fix things quietly.'),
    ('adventure', 'Drive Nowhere Together',              'The best drives usually have no destination.'),
    ('adventure', 'Kiss by the Falls',                   'Some places feel made for romance.'),
    ('adventure', 'Luxury Under the Stars',              'Hotel ceilings are overrated.'),
    ('adventure', 'Paddle Into Sunset',                  'Let the sunset do the talking.'),
    ('adventure', 'Find the Hidden Lake',                'Some places are better found together.'),
    ('adventure', 'Wild Night Together',                 'Nature gets wilder after dark.'),
    ('adventure', 'Refall in Love Weekend',              'Sometimes love just needs distance from routine.'),
    ('adventure', 'Rooftop Nights for Two',              'Just us above the city noise.'),
    ('adventure', 'Lovers Lost in the Hills',            'Lost signal. Found each other.'),
    ('adventure', 'One Night Without Phones',            'Look at each other, not your screens.'),
    ('adventure', 'Rain Drive & Tea',                    'Rain sounds better from inside a moving car.'),
    ('adventure', 'Couple Therapy in Nature',            'Nature heals conversations too.'),
    ('adventure', 'Candlelight by the Lake',             'Nights like this stay forever.'),
    ('adventure', 'Midnight Movie in the Wild',          'Cinema feels different under the stars.'),
    ('adventure', 'Jump First. Eat Later.',              'Fear tastes better after the jump.'),
    ('adventure', 'Fear Ends Tonight',                   'Tonight you finally do it.'),
    ('adventure', 'Into the Dark Jungle',                'The jungle changes after sunset.'),
    ('adventure', 'Climb Beyond Fear',                   'The hardest climb is usually mental.'),
    ('adventure', 'Fly Through the Canyon',              'Gravity loses for a few seconds.'),
    ('adventure', 'Freeze & Melt',                       'Cold mountains. Warm springs. Perfect balance.'),
    ('adventure', 'Beneath the Unknown',                 'Some worlds exist underground.'),
    ('adventure', 'Survive the Jungle Night',            'No comfort. Just instinct.'),
    ('adventure', 'Sleep on a Cliff Edge',               'Not everyone can sleep here.'),
    ('adventure', 'Ride the Wild River',                 'Hold tight and let go.'),
    ('adventure', 'Fly Above the Mountains',             'The view changes everything from up there.'),
    ('adventure', 'Desert Under the Stars',              'Silence feels massive in the desert.'),
    ('adventure', 'One Night Like Old Times',            'Like nothing ever changed.'),
    ('adventure', 'Birthday With Humans You Never Met',  'Weirdly unforgettable birthdays happen like this.'),
    ('adventure', 'Escape the Meeting Room',             'Your team needs this more than another Zoom call.'),
    ('adventure', 'Moms Gone Missing',                   'Moms deserve weekends too.'),
    ('adventure', 'Men, Mountains & Conversations',      'Some talks happen better outdoors.'),
    ('adventure', 'Back to Chaos Again',                 'Exactly like college. Slightly older.'),
    ('adventure', 'Strangers, Music & Bunk Beds',        'Nobody stays strangers for long here.'),
    ('adventure', 'Travel With Random People',           'Sometimes random plans become the best memories.'),
    ('adventure', 'Introverts Escape Together',          'Socializing without the pressure.'),
    ('adventure', 'Sunset & Deep Talks',                 'Sunset makes people honest somehow.'),
    ('adventure', 'No Friends? Join Us.',                'Everyone arrives alone at first.'),
    ('adventure', 'The Weekend Nobody Cancels',          'Finally, a plan everyone shows up for.');
