-- Migration: Seed experience_templates for the remaining moods
-- Added on: 2026-05-14
-- Description: Extends the adventure-only template set with titles + hook lines
-- for social, wellness, creative, culinary, cultural, fashion, fitness, and
-- family. Data sourced from the product team's Category Template workbook.
--
-- Idempotent: re-running deletes only the new mood rows then re-inserts.

DELETE FROM experience_templates
WHERE mood IN ('social', 'wellness', 'creative', 'culinary', 'cultural', 'fashion', 'fitness', 'family');

INSERT INTO experience_templates (mood, title, hook_line) VALUES
    ('social', 'Rooftop Dinner With Strangers', 'Good food. Better conversations. Zero awkwardness.'),
    ('social', 'Campfire & New Friends', 'Bonfire nights hit different with the right people.'),
    ('social', 'Long Drive Social', 'Loud music. Open roads. Good people.'),
    ('social', 'Social Villa Weekend', 'Escape the city. Meet people worth remembering.'),
    ('social', 'Stranger Picnic Day', 'Come for the picnic. Leave with stories.'),
    ('social', 'Sunset Social Club', 'Golden hour feels better together.'),
    ('social', 'Weekend With New People', 'The best weekends usually start unexpectedly.'),
    ('social', 'Music & Bonfire Night', 'Firelight, music, and zero rush.'),
    ('social', 'Group Trek & Chill', 'Climb together. Chill after.'),
    ('social', 'Friday Night Escape', 'Your weekend deserves a better story.'),
    ('social', 'Social Camping Weekend', 'Better people make better campfires.'),
    ('social', 'Dinner Party Experience', 'Great food starts great conversations.'),
    ('social', 'Random Group Adventure', 'No plans. Just chaos worth remembering.'),
    ('social', 'Social Night Drive', 'Midnight roads and conversations that keep going.'),
    ('social', 'Board Games & Pizza Night', 'Friendships end over board games sometimes.'),
    ('social', 'Weekend House Party', 'Not your usual party crowd.'),
    ('social', 'Coffee Meetup Experience', 'Coffee and conversations with no pressure.'),
    ('social', 'Stranger Birthday Party', 'Celebrate like everyone already knows each other.'),
    ('social', 'Friends-Making Trek', 'Mountains make strangers feel familiar.'),
    ('social', 'Young Founders Hangout', 'Big ideas need better rooms.'),
    ('social', 'Social Hostel Experience', 'Backpacker chaos without leaving the city.'),
    ('social', 'After-Work Social Escape', 'Your real life starts after work.'),
    ('social', 'Movie Night Under Stars', 'Cinema feels better outdoors.'),
    ('social', 'Group Sunset Kayaking', 'Sunset looks better from the water.'),
    ('social', 'Sunday Social Brunch', 'Soft Sundays. Good food. Better company.'),
    ('social', 'Invite-Only Dinner', 'Not everyone gets a seat at this table.'),
    ('social', 'Members-Only Weekend', 'Limited people. Unlimited stories.'),
    ('social', 'Secret Rooftop Party', 'Hidden location. Loud music. Good chaos.'),
    ('social', 'Luxury Villa Social', 'Weekend luxury meets social energy.'),
    ('social', 'Sunset Yacht Social', 'Luxury energy without trying too hard.'),
    ('social', 'One Night. No Rules.', 'Some nights shouldn’t be planned.'),
    ('social', 'Mystery Day Out', 'You’ll know the plan when the adventure starts.'),
    ('social', 'Spin-the-Wheel Weekend', 'Nobody knows what happens next.'),
    ('social', 'Stranger Squad Trip', 'Nobody stays strangers for long here.'),
    ('social', 'The Unplanned Road Trip', 'Best trips rarely start with a plan.'),
    ('social', 'Slow Sunday Escape', 'Slow mornings and zero pressure energy.'),
    ('social', 'Walk & Talk Evening', 'Some conversations need walking.'),
    ('social', 'Sunrise & Silence', 'Start the day before the world gets loud.'),
    ('social', 'Burnout Recovery Weekend', 'Burnout needs more than sleep.'),
    ('social', 'Offline Day Retreat', 'No notifications. Just real moments.'),
    ('social', 'Midnight Tea Run', 'Tea at midnight just hits differently.'),
    ('social', 'Rooftop Movie Night', 'Rooftops, movies, and city lights together.'),
    ('social', 'Café Hopping Club', 'One café always turns into three.'),
    ('social', 'Street Food Hunt', 'The best food usually has no ads.'),
    ('social', 'Sunrise Cycling Club', 'Ride early. Breakfast later.'),
    ('social', 'No Friends? Join Us.', 'Everyone arrives alone at first.'),

    ('wellness', 'Wellness Day With Me', 'A slower day for your mind and body.'),
    ('wellness', 'Slow Living Weekend', 'No rush. No pressure. Just slower living.'),
    ('wellness', 'Stress Reset Session', 'Because your mind deserves a break too.'),
    ('wellness', 'Nature Healing Escape', 'Nature fixes things quietly.'),
    ('wellness', 'Digital Detox Day', 'Log out for a while.'),
    ('wellness', 'Self-Care Sunday', 'Soft Sundays feel better.'),
    ('wellness', 'Sunrise Yoga With Me', 'Move gently with the morning light.'),
    ('wellness', 'Rooftop Yoga Session', 'Breathe above the noise of the city.'),
    ('wellness', 'Beach Yoga Morning', 'Start the day softer.'),
    ('wellness', 'Weekend Yoga Escape', 'Stretch, slow down, reconnect.'),
    ('wellness', 'Yoga & Tea Evening', 'Calm movement followed by calmer conversations.'),
    ('wellness', 'Beginner Yoga With Me', 'No pressure. Just breathe and begin.'),
    ('wellness', 'Meditation Evening With Me', 'Silence feels good sometimes.'),
    ('wellness', 'Silent Morning Retreat', 'Quiet mornings change your whole day.'),
    ('wellness', 'Mindfulness Walk With Me', 'Walk slower. Notice more.'),
    ('wellness', 'Calm Mind Session', 'Less noise inside your head.'),
    ('wellness', 'Deep Relaxation Meetup', 'A pause from everything overwhelming.'),
    ('wellness', 'Sunset Meditation Circle', 'End the day in complete stillness.'),
    ('wellness', 'Spa Day With Me', 'Relax properly for once.'),
    ('wellness', 'Luxury Self-Care Escape', 'Rest like you actually deserve it.'),
    ('wellness', 'Steam & Relax Evening', 'Warm steam and zero stress.'),
    ('wellness', 'Wellness Spa Weekend', 'Two days of complete reset energy.'),
    ('wellness', 'Massage & Recovery Session', 'Let your body finally relax.'),
    ('wellness', 'Relaxation Retreat With Me', 'Slow experiences heal differently.'),
    ('wellness', 'Breathwork Session With Me', 'Your breathing affects more than you think.'),
    ('wellness', 'Morning Breathing Club', 'Start calmer than yesterday.'),
    ('wellness', 'Deep Breathing Retreat', 'Slow breaths. Softer thoughts.'),
    ('wellness', 'Breathing & Meditation Circle', 'Quiet minds connect differently.'),
    ('wellness', 'Relax & Breathe Evening', 'Exhale the stress of the day.'),
    ('wellness', 'Breath Reset Experience', 'Sometimes you just need to pause.'),
    ('wellness', 'Digital Detox Weekend', 'Real life feels better offline.'),
    ('wellness', 'Detox Retreat With Me', 'Disconnect to reconnect properly.'),
    ('wellness', 'No Phone Sunday', 'One full day without notifications.'),
    ('wellness', 'Clean Mind Escape', 'Clear your head away from constant noise.'),
    ('wellness', 'Slow Weekend Retreat', 'Nothing urgent. Everything peaceful.'),
    ('wellness', 'Unplug & Recharge', 'Your brain needs recovery too.'),

    ('creative', 'Paint & Sip Night', 'Paint badly. Laugh loudly. Sip slowly.'),
    ('creative', 'Pottery Date Night', 'A little messy. A little romantic.'),
    ('creative', 'Girls Paint Night', 'Paint, gossip, snacks, repeat.'),
    ('creative', 'Couple Canvas Date', 'Two people. One canvas. Zero pressure.'),
    ('creative', 'Paint Your Partner', 'The results are usually hilarious.'),
    ('creative', 'Wine, Clay & Conversations', 'Soft music, clay hands, good company.'),
    ('creative', 'DIY Candle Making Night', 'Make candles that smell like your personality.'),
    ('creative', 'Tote Bag Painting Day', 'Wear your own art home.'),
    ('creative', 'Matcha & Painting Club', 'Calm drinks and calmer creativity.'),
    ('creative', 'Art Café Meetup', 'Coffee first. Creativity after.'),
    ('creative', 'Midnight Paint Session', 'Art feels different after dark.'),
    ('creative', 'Paint the Sunset', 'Capture the sky before the light disappears.'),
    ('creative', 'Clay & Chill With Me', 'Slow conversations and messy hands.'),
    ('creative', 'Sip & Sketch Evening', 'Casual sketches and easy conversations.'),
    ('creative', 'Couples Pottery Session', 'Romance, clay, and slightly ruined outfits.'),
    ('creative', 'Creative Date With Me', 'A date that actually feels memorable.'),
    ('creative', 'Aesthetic DIY Day', 'Pinterest dreams but in real life.'),
    ('creative', 'Build Your Own Decor', 'Make something your room will thank you for.'),
    ('creative', 'Paint, Music & Pizza', 'Three things nobody says no to.'),
    ('creative', 'Canvas & Coffee Morning', 'Soft mornings for creative people.'),
    ('creative', 'Friendship Bracelet Night', 'Tiny bracelets. Big nostalgic energy.'),
    ('creative', 'Fashion Illustration Meetup', 'Sketch ideas like your own mini fashion studio.'),
    ('creative', 'Make Your Own Perfume', 'Create a scent nobody else has.'),
    ('creative', 'Neon Paint Party', 'Glow paint, loud music, zero seriousness.'),
    ('creative', 'The Pinterest Day Out', 'Everything looks aesthetic today.'),

    ('culinary', 'Eat With Me', 'Good food tastes better with good company.'),
    ('culinary', 'Street Food Night', 'One city. Ten flavors. Endless stories.'),
    ('culinary', 'Midnight Food Run', 'Hunger hits different after midnight.'),
    ('culinary', 'Hotpot Dinner Experience', 'Hot food. Cold weather. Real conversations.'),
    ('culinary', 'Sushi Night With Me', 'Small bites, slow conversations, good vibes.'),
    ('culinary', 'BBQ & Bonfire Night', 'Fire, food, music, and people worth meeting.'),
    ('culinary', 'Café Hopping Day', 'From one aesthetic café to another.'),
    ('culinary', 'Breakfast With Strangers', 'Start your morning with unfamiliar faces and fresh energy.'),
    ('culinary', 'Pizza Making Night', 'Make pizza. Make memories.'),
    ('culinary', 'Cook With Me', 'Cooking together feels strangely personal.'),
    ('culinary', 'Fine Dining Experience', 'Dress well. Eat slow. Enjoy the night.'),
    ('culinary', 'Rooftop Dinner Night', 'City lights and conversations above the noise.'),
    ('culinary', 'Dessert Crawl Experience', 'Sugar, laughter, and late-night cravings.'),
    ('culinary', 'Tea & Conversations Evening', 'Slow tea. Slower conversations.'),
    ('culinary', 'Seafood Feast Night', 'Fresh seafood and unforgettable table vibes.'),
    ('culinary', 'Korean BBQ Night', 'Grill together. Laugh louder. Eat endlessly.'),
    ('culinary', 'Brunch Club Experience', 'Weekends deserve better breakfasts.'),
    ('culinary', 'Homemade Dinner Experience', 'Comfort food and comforting company.'),
    ('culinary', 'Coffee & Croissants Morning', 'Soft mornings begin with coffee and calm people.'),
    ('culinary', 'Farm-to-Table Experience', 'Eat closer to nature.'),
    ('culinary', 'Wine & Cheese Evening', 'Elegant evenings deserve better conversations.'),
    ('culinary', 'Chef’s Table Experience', 'A dining experience beyond the menu.'),
    ('culinary', 'Food Truck Hopping', 'Chase flavors across the city streets.'),
    ('culinary', 'Biryani Night Out', 'Because biryani is never a solo plan.'),
    ('culinary', 'Dinner & Long Drive', 'Some nights should never end.'),

    ('cultural', 'My Favorite Places in the City', 'The places I never get bored of.'),
    ('cultural', 'City Nights With Me', 'Food, drives, lights, and whatever happens next.'),
    ('cultural', 'Let Me Show You My City', 'Experience the city like someone who actually lives it.'),
    ('cultural', 'The City I Never Get Tired Of', 'Some places never lose their magic.'),
    ('cultural', 'My Secret Food Spots', 'The places I almost don’t want to share.'),
    ('cultural', 'Come Get Lost With Me', 'No fixed plan. Just good places and good moments.'),
    ('cultural', 'Places I Go When Life Feels Heavy', 'Quiet corners for difficult days.'),
    ('cultural', 'My Perfect Sunday in the City', 'Coffee, food, walks, and a slow city mood.'),
    ('cultural', 'The City After Midnight', 'Because cities feel different after dark.'),
    ('cultural', 'The Non-Tourist City Experience', 'No tourist traps. Just real city energy.'),
    ('cultural', 'Rooftops, Roads & Random Talks', 'Some conversations happen better at night.'),
    ('cultural', 'Cafés I’d Gatekeep Forever', 'Hidden cafés worth leaving home for.'),
    ('cultural', 'My Comfort Places', 'The places that mentally reset me.'),
    ('cultural', 'One Night Around My City', 'A full night of food, lights, and movement.'),
    ('cultural', 'The Real Version of This City', 'The city locals actually enjoy.'),
    ('cultural', 'Places Worth Leaving Home For', 'Not famous. Just unforgettable.'),
    ('cultural', 'My Kind of Weekend', 'Exactly how I’d spend a perfect weekend.'),
    ('cultural', 'The City Through My Eyes', 'A personal version of the city most people miss.'),
    ('cultural', 'Long Drive, Loud Music, City Lights', 'The perfect night usually starts like this.'),
    ('cultural', 'Come Romanticize the City With Me', 'Slow walks, good food, cinematic moments.'),
    ('cultural', 'The Hidden Side of the City', 'Places the algorithm never shows you.'),
    ('cultural', 'If I Had One Day to Show You This City', 'The only city plan you’ll need.'),
    ('cultural', 'The City Feels Better at Night', 'Night changes everything.'),
    ('cultural', 'Places That Deserve More Attention', 'Underrated spots with unforgettable energy.'),
    ('cultural', 'My Escape Spots Around the City', 'The places I disappear to sometimes.'),

    ('fashion', 'Dress Me Better', 'Your wardrobe deserves better decisions.'),
    ('fashion', 'Hotter Than Last Week', 'Small style changes change everything.'),
    ('fashion', 'Rich Girl Shopping Day', 'Dress expensive. Feel unstoppable.'),
    ('fashion', 'Main Character Styling', 'Start dressing like the camera is always on you.'),
    ('fashion', 'Glow-Up With Me', 'New outfits. New energy.'),
    ('fashion', 'Bad Outfit Recovery Session', 'We need to talk about your wardrobe.'),
    ('fashion', 'Dress Like You Have Money', 'Luxury energy without luxury prices.'),
    ('fashion', 'Your Closet Needs Help', 'Half your clothes need a second opinion.'),
    ('fashion', 'Shopping Like Pinterest', 'Pinterest boards but in real life.'),
    ('fashion', 'Look Expensive With Me', 'Stylish doesn’t have to mean overpriced.'),
    ('fashion', 'Soft Girl Shopping Day', 'Soft colors, cute fits, slow café energy.'),
    ('fashion', 'Clean Boy Style Session', 'Simpler fits. Sharper presence.'),
    ('fashion', 'Date Night Outfit Fix', 'Dress like the night actually matters.'),
    ('fashion', 'Pretty Fits & Coffee', 'Good outfits deserve good cafés.'),
    ('fashion', 'Fashion Therapy With Me', 'Sometimes confidence starts with clothes.'),
    ('fashion', 'Hot Girl Closet Reset', 'Out with the old personality.'),
    ('fashion', 'Dress Better. Feel Better.', 'Your outfit changes how you walk into rooms.'),
    ('fashion', 'Outfit Hunting With Me', 'Find pieces worth repeating constantly.'),
    ('fashion', 'Luxury Looks on a Budget', 'Expensive taste. Smarter spending.'),
    ('fashion', 'Instagram Outfit Day', 'Build looks your camera roll will love.'),
    ('fashion', 'Mall Day But Better', 'Shopping, coffee, photos, repeat.'),
    ('fashion', 'Style Me Like Your Ex', 'The revenge glow-up starts here.'),
    ('fashion', 'Find Your Signature Look', 'Stop dressing like everyone else.'),
    ('fashion', 'The “I Need New Clothes” Day', 'Because your current wardrobe isn’t surviving another season.'),
    ('fashion', 'Fashion, Photos & Matcha', 'Aesthetic day from head to toe.'),

    ('fitness', 'Gym With Me', 'Train harder with someone beside you.'),
    ('fitness', 'Morning Run With Me', 'Start the day before the city wakes up.'),
    ('fitness', 'Sunset Workout Session', 'Sweat through golden hour.'),
    ('fitness', 'Fitness & Breakfast', 'Earn your breakfast properly.'),
    ('fitness', 'Walk & Coffee With Me', 'Slow steps and easy conversations.'),
    ('fitness', 'Leg Day With Me', 'Tomorrow’s pain starts today.'),
    ('fitness', 'Couples Workout Session', 'Sweat together. Stay together.'),
    ('fitness', 'Weekend Fitness Meetup', 'Better weekends begin with movement.'),
    ('fitness', 'Outdoor Training Session', 'Fresh air hits different during workouts.'),
    ('fitness', 'Beach Run Club', 'Run where the city feels far away.'),
    ('fitness', 'Fat Burn Cardio Session', 'High heartbeats. Zero excuses.'),
    ('fitness', 'Beginner Gym Session', 'Start somewhere. Start today.'),
    ('fitness', 'Abs Workout With Me', 'Core burning. Confidence loading.'),
    ('fitness', 'Strength Training Meetup', 'Lift heavy. Feel stronger.'),
    ('fitness', 'Night Gym Session', 'The gym feels different after dark.'),
    ('fitness', 'Sunday Recovery Walk', 'Slow down before Monday begins again.'),
    ('fitness', 'Running & Stretch Session', 'Push your body. Reset your mind.'),
    ('fitness', 'Fitness Date', 'A healthier kind of date.'),
    ('fitness', 'Group Walk Meetup', 'Movement feels easier together.'),
    ('fitness', 'Workout & Protein Shake', 'Sweat first. Shake after.'),
    ('fitness', 'Park Workout With Me', 'No machines. Just movement.'),
    ('fitness', 'Girls Workout Meetup', 'Strong girls train together.'),
    ('fitness', 'Boys Training Session', 'Built through discipline and consistency.'),
    ('fitness', 'Sweat Session After Work', 'Leave office stress on the gym floor.'),
    ('fitness', 'Fitness Challenge Day', 'Compete, sweat, survive, repeat.'),

    ('family', 'Little Chefs Day Out', 'Tiny hands making big kitchen memories.'),
    ('family', 'Messy Hands Club', 'The messier the day, the happier the kids.'),
    ('family', 'Tiny Campers Adventure', 'Small tents. Big adventures.'),
    ('family', 'Pizza, Games & Giggles', 'Cheese, chaos, and nonstop laughter.'),
    ('family', 'Mini Explorers Club', 'Curious kids belong outdoors.'),
    ('family', 'Jump, Run & Play Day', 'Energy levels: impossible to control.'),
    ('family', 'Kids Gone Wild', 'Let them run, scream, and just be kids.'),
    ('family', 'Paint, Play & Party', 'Colors everywhere and nobody cares.'),
    ('family', 'Little Artists Playground', 'Creativity without rules or clean clothes.'),
    ('family', 'Mud, Magic & Memories', 'Dirt today. Core memories forever.'),
    ('family', 'Tiny Detectives Hunt', 'Clues, surprises, and little detectives everywhere.'),
    ('family', 'Pancakes & Pajamas Morning', 'Slow mornings made for smiles and syrup.'),
    ('family', 'Splash & Play Party', 'Water everywhere. Happiness guaranteed.'),
    ('family', 'Little Builders Club', 'Tiny creators building big imaginations.'),
    ('family', 'Cartoon & Chaos Evening', 'Snacks, cartoons, and beautiful chaos.'),
    ('family', 'Dino Adventure Day', 'A prehistoric day full of roaring fun.'),
    ('family', 'Slime Time Experience', 'Sticky hands. Happy faces.'),
    ('family', 'Superhero Training Camp', 'Every kid gets to feel unstoppable today.'),
    ('family', 'Candy, Crafts & Fun', 'Sugar rush meets creative chaos.'),
    ('family', 'Kids Jungle Adventure', 'Explore, climb, and get wonderfully dirty.'),
    ('family', 'Mini Bakers Party', 'Tiny bakers making sweet little masterpieces.'),
    ('family', 'Toy Story Play Day', 'Toys, teamwork, and endless imagination.'),
    ('family', 'Rain Dance Kids Party', 'Because puddles are more fun than screens.'),
    ('family', 'Little Monsters Fun Club', 'Loud laughs and lovable little chaos.'),
    ('family', 'Magic & Balloon Day', 'A day that feels straight out of a cartoon.');
